### PR TITLE
SE-2170 Port changes not yet merged to upstream into our juniper release branch #225

### PR DESCRIPTION
**Pull request by pomegranited**
This branch starts with the tagged upstream `open-release/juniper.2`, and adds in the code drift that was present in `opencraft-release/ironwood.2` which has not yet been merged upstream.

See https://github.com/open-craft/edx-platform/pull/225 for testing instructions.

**Reviewer**

- [x] @nizarmah 

CC @lgp171188

### CODE REVIEW

**Comment by nizarmah** [comment]
There doesn't seem to be any Pull Requests in those cherry picked commits. Do I just need to just follow the test instructions on open-craft/edx-platform#225, without testing anything in this pull request? Please let me know when possible @pomegranited

**Comment by pomegranited** [comment]
@nizarmah 

> There doesn't seem to be any Pull Requests in those cherry picked commits

Sorry, I didn't edit the cherry-picked commits for this repo to add the pull request #. But if you follow the "cherry-picked from" revision link, github will show you the open PR it's related to.

For the ecommerce one, I haven't taken the trouble of setting up ecommerce on this test instance, because that's a bit involved. If you could just check that the cherry-pick went in cleanly and that the variable is still in use in the ecommerce config, that should be enough.

**Comment by nizarmah** [comment]
Alright, no worries @pomegranited, thank you for getting back to me about this though!

**Comment by nizarmah** [comment]
Status of reviewing the cherry picked commits:
- [x] [e805a57](https://github.com/open-craft/configuration/commit/e805a57a66dac62b6d96afce5c4bc4278147621f) | edx#5706
- [x] [40c5a89](https://github.com/open-craft/configuration/commit/40c5a8993d6cc2f9ab8197bd72e83bb018a91f60) | #110
- [x] [436092e](https://github.com/open-craft/configuration/commit/436092e2ab1a4dd8db3e5e077dfb6d8dd7151d71) | #119
- [ ] [8a79772](https://github.com/open-craft/configuration/commit/8a797720dd6d312222e4aa35fecdb45c6e358d90) | edx#5807
- [x] [af69623](https://github.com/open-craft/configuration/commit/af69623be7a0f4deebd2e0667f205ebe24aa0f0d) | edx#5837
- [x] [a027b4b](https://github.com/open-craft/configuration/commit/a027b4b6677231c5238013488888566b9cd05aff) | edx#5884

#

Regarding commit [`436092e`](https://github.com/open-craft/configuration/commit/436092e2ab1a4dd8db3e5e077dfb6d8dd7151d71), I followed the following testing instructions as advised by @pomegranited 
> For the ecommerce one, I haven't taken the trouble of setting up ecommerce on this test instance, because that's a bit involved. If you could just check that the cherry-pick went in cleanly and that the variable is still in use in the ecommerce config, that should be enough.

I can confirm that the variable is still in use in the ecommerce config on [`open-release/juniper.2` branch](https://github.com/open-craft/ecommerce/blob/4a7caa4157e7f1c127ad5bef557ed76b81eaab00/ecommerce/settings/production.py#L100).

# 

Regarding commit [`8a79772`](https://github.com/open-craft/configuration/commit/8a797720dd6d312222e4aa35fecdb45c6e358d90), an AWS Setup is required. Therefore, testing it will be postponed to when the ASU YTP instance is upgraded to Juniper. Discussion regarding this can be found [here](https://chat.opencraft.com/opencraft/pl/3cog9df94byki8xk1ka8ic115w).

**Review by nizarmah — APPROVED** [review]
:+1:

- [x] I tested this through:
>    - Testing each _cherry picked_ commit's pull request:
>        - Read through the code
>        - Followed the testing instructions for each pull request

- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [ ] ~~Includes documentation~~
- [ ] ~~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

**Comment by nizarmah** [comment]
Status of reviewing the latest cherry picked commits:
- [ ] [a027b4b](https://github.com/open-craft/configuration/commit/a027b4b6677231c5238013488888566b9cd05aff) | edx#5884

**Review by nizarmah — APPROVED** [review]
I tested the latest cherry picked commit [`a027b4b`](https://github.com/open-craft/configuration/commit/a027b4b6677231c5238013488888566b9cd05aff) regarding "Remove repeated course data dir creation step", in the following way:
- Tested each *cherry picked* commit as mentioned previously
- Tried Importing/Exporting Courses in Studio


:+1:

**Pull request merged**
