### PR TITLE
Make it possible to add custom settings to site configuration for Studio and LMS.

### PR DESCRIPTION
**Pull request by itsjeyd**
Part of the scope of [OC-2506](https://tasks.opencraft.com/browse/OC-2506).

**Reviewers**

- [x] @bdero

### CODE REVIEW

**Comment by bdero** [comment]
:+1:

**Comment by itsjeyd** [comment]
Thanks @bdero! Merging now.

**Comment by antoviaque** [comment]
@bdero Same thing - could you include a link to the upstream PR?

**Comment by bdero** [comment]
Upstream PR is: https://github.com/edx/configuration/pull/3872

**Comment by antoviaque** [comment]
@bdero Thank you!

**Pull request merged**
