### PR TITLE
Adds SANDBOX_ENABLE_CERTIFICATES

### PR DESCRIPTION
**Pull request by pomegranited**
Gives the option to disable the certificates process to reduce load on xqueue, and this RabbitMQ and MySQL (for sessions, cf OC-3840).

Defaults to `true`, so no change to standard behaviour.

**JIRA issues**: OC-3839

**Sandbox URLs**:

* LMS: https://jinja-fix.stage.opencraft.hosting/
* Studio: https://studio-jinja-fix.stage.opencraft.hosting/

[Appserver 15](https://stage.console.opencraft.com/instance/1400/edx-appserver/531/)

### CODE REVIEW

**Comment by pomegranited** [comment]
:+1:

- [x] I tested this by:
  * adding `SANDBOX_ENABLE_CERTIFICATES: false` to the instance settings
  * spawning a [new appserver](https://stage.console.opencraft.com/instance/1400/edx-appserver/531/)
  * checking the provisioned appserver to ensure that the certificates service is neither installed nor running.
  * watched the logs to ensure that the regular pings to `/xqueue` are no longer occurring.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A

**Comment by smarnach** [comment]
:+1: This looks good to me.  I read the code and the deployment log of the new app server you deployed, and I logged into the app server and verified that certs was not installed on the instance.

**Comment by pomegranited** [comment]
This change can be reverted since OC-3857, but is harmless left in place.  No need to carry it forward into the Hawthorn release branch.

**Comment by tomaszgy** [comment]
@pomegranited Speaking of that, could you please explain me how we are going to create `opencraft-release/hawthorn.1`? Will it be based on future `edx:open-release-hawthorn.master` with our changes cherry-picked from `opencraft-release/ginkgo.1`? [As it seems that our fork is a bit different](https://github.com/edx/configuration/compare/open-release/ginkgo.master...open-craft:opencraft-release/ginkgo.1).

**Comment by pomegranited** [comment]
@tomaszgy  Yep, we've got changes from a few places that are pending approval from edX, and it's critical that we include them in our hawthorn release branch.

Will need to go through each difference individually and track down its upstream status, and cherry-pick it carefully, resolving conflicts as we go.  There's one that's tricky: the aws/s3 logging change PR from OC-2004 has been split into two separate tickets, and only one replacement PR has been created so far.  But I can help with this at the time.

**Pull request merged**
