### PR TITLE
Simplify path expression

### PR DESCRIPTION
**Pull request by clemente**
Porting simple fix from https://github.com/edx/configuration/pull/4052#pullrequestreview-75970269

### CODE REVIEW

**Comment by smarnach** [comment]
@clemente Code looks good.  Do the integration tests cover this functionality?  If so, I'm fine with merging, since the tests are passing.

**Comment by clemente** [comment]
@smarnach I spent a while looking for edx/configuration tests, and I found only [3 files](https://github.com/edx/configuration/tree/master/tests), and `make test` which runs something on Docker but doesnt't verify much; then I realized probably you mean *Ocim's* integration tests; sorry about the misunderstanding. And yes, they test static file downloading, because the default logo+favicon are in SWIFT, and simple_theme will download them and the tests will [check](https://github.com/open-craft/opencraft/blob/clemente/ui-choose-colors/instance/tests/integration/integration_instance.py#L237) that the files be in the correct place. So yes, the part about the URLs is covered.

**Comment by smarnach** [comment]
@clemente I'm referring to the Ocim integration tests.  This PR targets the Ocim integration test branch.

I was a little confused as well, since PRs to this branch of course don't trigger Ocim CI runs.  Is there a reasonable way to test this without merging it?  If not, we can merge it, test it, and roll back if the tests fail.

**Comment by clemente** [comment]
@smarnach The way I tested it is with a local script, to compare that the old regexp and the `dirname` work the same in many cases (`dirname` actually works better in the case there's no directory because it returns an empty string):
```
# Test dirname
# Save to dirname.yml and run it with:
# ansible-playbook dirname.yml -c local
#
---
- hosts: all
  vars:
    SIMPLETHEME_STATIC_FILES_URLS:
      - url: http://docs.ansible.com/ansible/latest/_static/images/logo_invert.png
        dest: lms/static/images/logo.png
      - url: http://docs.ansible.com/favicon.ico
        dest: lms/static/images/favicon.ico
      - url: http://docs.ansible.com/favicon2.ico
        dest: images/favicon2.ico
      - url: http://docs.ansible.com/favicon3.ico
        dest: favicon3.ico
      - url: http://docs.ansible.com/favicon4.ico
        dest: one/../two/favicon3.ico
  tasks:
  - name: Testing1
    debug:
      msg: "{{item.dest}} changes to: {{ item.dest | dirname }}. The original was: {{ item.dest | regex_replace('/[^/]*$','') }}"
    with_items: "{{ SIMPLETHEME_STATIC_FILES_URLS }}"
  - debug:
      msg: "fin"
```

**Comment by smarnach** [comment]
@clemente OK, this test looks good, so :+1:.

I'm merging this now.  Can you please trigger a CircleCI run for Ocim (e.g. by creating a PR with an irrelevant change to the README file) to test this did not break the integration tests?

**Pull request merged**
