### PR TITLE
Frank/fix syncing logs to s3 v2

### PR DESCRIPTION
**Pull request by Metfriet**
Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by lgp171188** [comment]
@Metfriet, this PR has commits other than your commits, probably picked from a wrong branch. Can you fix this, create a new branch with only the changes needed for this PR? For instance, this commit https://github.com/open-craft/configuration/commit/5dc9f1fa1bbd7a3172b1c6cc37455ef65d82306f in the `epodx-hawthorn.2` branch already has the changes for the `COMMON_ENABLE_AWS_INTEGRATION` variable already

**Comment by Metfriet** [comment]
@lgp171188 I've cleaned up the branch so only the required changes are present.

**Comment by lgp171188** [comment]
@Metfriet, something is not okay with this PR now. The target branch is that of epodX but the changes appear to be for HMS. Please fix this and let me know once you have done that.

**Comment by Metfriet** [comment]
@lgp171188 I tried to merge the same branch with fixes into two different branches but that is creating a lot of problems now unfortunately, so I made a new branch with a new PR for epodx here: https://github.com/open-craft/configuration/pull/62 and I will close this one. Sorry for the inconvenience.

**Pull request closed without merging**
