### PR TITLE
[BB-6112] Prepare `opencraft-release/maple.3` branches for configuration

### PR DESCRIPTION
**Pull request by 0x29a**
## Description

This PR prepares the shared `opencraft-release/maple.3` branch for our fork of https://github.com/openedx/configuration.

[Code-drift commits](https://github.com/openedx/configuration/compare/open-release/lilac.2...open-craft:opencraft-release/lilac.2) (from the oldest to the newest):

| №   | Commit                                                                                              | Upstream PR                                                | Included in `open-release/maple.3`                                                                 | Should be cherry-picked? | Notes                                                                                                                                                                                                                                                                                                                                                   |
| --- | --------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- | -------------------------------------------------------------------------------------------------- | ------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1   | openedx/configuration@694e6ce675a47cf55a69951d773a3fec0917b91b | [link](https://github.com/openedx/configuration/pull/6400) | ✅ openedx/configuration@f731c07c83191d7fcc822a9e605744ed4ce9d318 | ❌                       |                                                                                                                                                                                                                                                                                                                                                         |
| 2   | openedx/configuration@a07798c0f2b9a09ee5e65603861e1901da05e910 | ❌                                                         | ❌                                                                                                 | ✅                       |                                                                                                                                                                                                                                                                                                                                                         |
| 3   | openedx/configuration@0573de14b7d0e6d4d95e68b222c21c0b61769a3f | ❌                                                         | ❌                                                                                                 | ✅                       | We might not need this: [1](https://tasks.opencraft.com/browse/BB-5799?focusedCommentId=204651&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-204651), [2](https://tasks.opencraft.com/browse/BB-5857?focusedCommentId=247508&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-247508). |
| 4   | openedx/configuration@1116e7532942b0c8c4dc41c4fd24368089f9b768 | [link](https://github.com/openedx/configuration/pull/6473) | ✅ openedx/configuration@adde3a293bf938cec10e9087323efcd67eb8eea9 | ❌                       | [Details](https://tasks.opencraft.com/browse/BB-5813?focusedCommentId=247512&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-247512).                                                                                                                                                                                     |
| 5   | openedx/configuration@e0219d192575a0f89317c7a257ccbd8e9ee0958e | [link](https://github.com/openedx/configuration/pull/6449) | ✅ openedx/configuration@b0f7e53b833e691b1d50832b116580cfdb601eb9 | ❌                       |                                                                                                                                                                                                                                                                                                                                                         |
| 6   | openedx/configuration@b2e860655d3d85c3435953cc80edce125e2f991d | [link](https://github.com/openedx/configuration/pull/6473) | ✅ openedx/configuration@adde3a293bf938cec10e9087323efcd67eb8eea9 | ❌                       | No need to cherry-pick. See the notes for the commit №4.                                                                                                                                                                                                                                                                                                |
| 7   | openedx/configuration@b5eeb9bbb26d9458f418a57dc362660f7b3a8b93 | ❌                                                         | ❌                                                                                                 | ❌                       | No need to cherry-pick. See the commit №8.                                                                                                                                                                                                                                                                                                              |
| 8   | openedx/configuration@06fb8f4f4921601695586f080c2a6e68045c1602 | ❌                                                         | ❌                                                                                                 | ✅                       | Requires cherry-picking and the version update.                                                                                                                                                                                                                                                                                                         |
| 9   | openedx/configuration@0252892fbbf2051280765a7280a851eb0bf013ed | ❌                                                         | ❌                                                                                                 | ❌                       | Merge commit, no need to cherry-pick.                                                                                                                                                                                                                                                                                                                   |
| 10  | openedx/configuration@d078cb2325a514381daa86ae6627118cdfb689c3 | [link](https://github.com/openedx/configuration/pull/6660) | ✅ openedx/configuration@2587f235d3e89600bb37af5a572b077813513774 | ❌                       |                                                                                                                                                                                                                                                                                                                                                         |
| 11  | openedx/configuration@c50b638dbe93fccf6caa8fe857a649c120ebd8f8 | [link](https://github.com/openedx/configuration/pull/6660) | ✅ openedx/configuration@2587f235d3e89600bb37af5a572b077813513774 | ❌                       |                                                                                                                                                                                                                                                                                                                                                         |
| 12  | openedx/configuration@30e9994a47e2aa0486fe258897a485fa58676b06 | [link](https://github.com/openedx/configuration/pull/6686) | ✅ openedx/configuration@5bd115646b87364babd93815fda1b1993dd32a12 | ❌                       |                                                                                                                                                                                                                                                                                                                                                         |
| 13  | openedx/configuration@dd6bb7a6bbdfc900688fdd6429637ef5e1d5fed4 | [link](https://github.com/openedx/configuration/pull/6677) | ❌                                                                                                 | ✅                       | We've missed backporting this to Maple.                                                                                                                                                                                                                                                                                                                 |
| 14  | openedx/configuration@b551572e2978d260f896eb1b2876e51e6d40896e | [link](https://github.com/openedx/configuration/pull/6686) | ✅ openedx/configuration@5bd115646b87364babd93815fda1b1993dd32a12 | ❌                       | Merge commit, no need to cherry-pick.                                                                                                                                                                                                                                                                                                                   |
| 15  | openedx/configuration@98dab5f344f34b3b8276a97bc307198bd6a65e22 | [link](https://github.com/openedx/configuration/pull/6677) | ❌                                                                                                 | ❌                       | Merge commit, no need to cherry-pick.                                                                                                                                                                                                                                                                                                                   |
| 16  | openedx/configuration@9933e7c926e04fc62cb1bcc58bb01cc89ee65544 | [link](https://github.com/openedx/configuration/pull/6679) | ❌                                                                                                 | ✅                       | Created after the `open-release/maple.3` tagging.                                                                                                                                                                                                                                                                                                       |
| 17  | openedx/configuration@3d6a26f190b7ee10f9fa0078075bd1a137f6cc9b | [link](https://github.com/openedx/configuration/pull/6679) | ❌                                                                                                 | ❌                       | Merge-commit, no need to cherry-pick.                                                                                                                                                                                                                                                                                                                   |
| 18  | openedx/configuration@4bb4424565f547a159e27d03bd9273cea37a607f | [link](https://github.com/openedx/configuration/pull/6708) | ❌                                                                                                 | ✅                       | Created after the `open-release/maple.3` tagging.                                                                                                                                                                                                                                                                                                       |
| 19  | openedx/configuration@1dbf3ba3a322bc0c04c8c241a309a82eac0be3c9 | [link](https://github.com/openedx/configuration/pull/6708) | ❌                                                                                                 | ❌                       | Merge-commit, no need to cherry-pick.                                                                                                                                                                                                                                                                                                                   |
| 20  | openedx/configuration@8107593c8c37c3488ff76a3b04489f37cc9cb93e | [link](https://github.com/openedx/configuration/pull/6717) | ❌                                                                                                 | ✅                       | Created after the `open-release/maple.3` tagging.                                                                                                                                                                                                                                                                                                       |
| 21  | openedx/configuration@7e34794188b9e5ee12f48d95a3c1ed4c7ae9864a | [link](https://github.com/openedx/configuration/pull/6586) | ❌                                                                                                 | ❌                       | This hasn't been backported to Maple. See [BB-6123](https://tasks.opencraft.com/browse/BB-6123).                                                                                                                                                                                                                                                        |

Total number of commits to cherry-pick: 7.

~~Note: I had to cherry-pick the additional commit (https://github.com/open-craft/configuration/pull/193/commits/2d7caab094a57136b3d442b0024b62e61b2321f6), which is the part of the commit 21. [Details](https://tasks.opencraft.com/browse/SE-4860?focusedCommentId=246885&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-246885).~~

## Testing instructions

- Commit №2: https://github.com/open-craft/configuration/pull/154
- Commit №3: https://github.com/open-craft/configuration/pull/159
- Commit №8: the sandbox provisioning should complete successfully.
- Commit №13: https://github.com/openedx/edx-platform/pull/29851
- Commit №16: https://github.com/openedx/configuration/pull/6679
- Commit №18: https://github.com/openedx/configuration/pull/6708
- Commit №20: the sandbox provisioning should complete successfully.

## Other information

Suggested sandbox configuration:
```yaml
# needed for the testing of https://github.com/open-craft/configuration/pull/154
newrelic_query_key: ""
newrelic_query_api_url: ""
uptime_report_s3_bucket: ""

# needed for the testing of https://github.com/open-craft/configuration/pull/159
EDXAPP_REINDEX_ALL_COURSES: true
EDXAPP_FEATURES_EXTRA:
  ENABLE_COURSEWARE_INDEX: true
  ENABLE_COURSEWARE_SEARCH: true
  ENABLE_DASHBOARD_SEARCH: true
  ENABLE_LIBRARY_INDEX: true

# needed for the testing of https://github.com/openedx/configuration/pull/6679
# https://github.com/openedx/configuration/pull/6708
# https://github.com/openedx/configuration/pull/6677
# and https://github.com/openedx/edx-platform/pull/29851
EDXAPP_DEFAULT_SITE_THEME: simple-theme
SIMPLETHEME_ENABLE_DEPLOY: true
EDXAPP_COMPILE_JSI18N: true
EDXAPP_COMPREHENSIVE_THEME_LOCALE_PATHS:
  - "{{ EDXAPP_COMPREHENSIVE_THEME_DIRS[0] }}/conf/locale"
EDXAPP_PREPEND_LOCALE_PATHS:
  - /edx/src/
  - "{{ EDXAPP_COMPREHENSIVE_THEME_DIRS[0] }}/simple-theme/i18n/conf/locale"
SIMPLETHEME_I18N_DJANGO:
  - lang: ar
    domain: django
    headers: |
      "Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\n"
    messages: |
      msgid "View Course"
      msgstr "XXX استعراض المحتوى"
  - lang: ar
    domain: djangojs
    headers: |
      "Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\n"
    messages: |
      msgid "Submit"
      msgstr "تقديم YYY"
      msgid "Add a Post"
      msgstr "إضافة منشور ZZZ"
```

### CODE REVIEW

**Comment by 0x29a** [comment]
Testing notes:
- ✅ https://github.com/open-craft/configuration/pull/154: **I had to replace `python` with `python3`** in `playbooks/roles/uptime_report/templates/uptime_report_script.j2` to make this work. I've added the fix to the respective commit. Then, created New Relic query key, and tested that `/edx/var/upload_uptime_report.py` created and uploaded the [uptime report](https://s3.console.aws.amazon.com/s3/buckets/ocim-maple3-opencraft-hosting?region=eu-west-1&prefix=uptime/&showversions=false) to the bucket.
- ✅ https://github.com/open-craft/configuration/pull/159: I had to add features manually to the `/edx/etc/lms.yml`, as I made a mistake in a suggested configuration, and executed `python manage.py cms reindex_course --all`. It worked fine.
- ✅ https://github.com/openedx/edx-platform/pull/29851: Followed the original test instructions, was able to see French translation instead of Spanish. Note: cookie name was different.
- ✅ https://github.com/openedx/configuration/pull/6679: Was able to see `XXX استعراض المحتوى` with `ar` locale enabled.
- ✅ https://github.com/openedx/configuration/pull/6708: Was able to see `إضافة منشور ZZZ` and `تقديم YYY`.

**Comment by 0x29a** [comment]
@mtyaka, I'm trying to test https://github.com/openedx/configuration/pull/6679 and https://github.com/openedx/configuration/pull/6708 using [this sandbox](https://manage.opencraft.com/instance/34580/edx-appserver/23586/), but, despite seeing the expected `django.po` and `djangojs.po` (along the compiled `.mo` files) in `/edx/var/edxapp/themes/simple-theme/i18n/conf/locale/ar/LC_MESSAGES`, I don't see `YYY` and `ZZZ` with `ar` locale enabled. Do you know what I can be missing?

**Comment by mtyaka** [comment]
@0x29a I think the reason you're not seeing the custom translations is that you need to use `EDXAPP_PREPEND_LOCALE_PATHS` instead of `EDXAPP_COMPREHENSIVE_THEME_LOCALE_PATHS`, otherwise the default translations take precedence.
For reference, custom translations are set up on [this instance](https://manage.opencraft.com/instance/27810/).

**Comment by 0x29a** [comment]
@mtyaka, ah, looks like the sandbox config [here](https://github.com/openedx/configuration/pull/6679) has a mistake (it doesn't set `EDXAPP_PREPEND_LOCALE_PATHS`)?

Anyway, I moved locale paths from `COMPREHENSIVE_THEME_LOCALE_PATHS` to  `PREPEND_LOCALE_PATHS`, ran `compilejsi18n` and `/edx/bin/edxapp-update-assets` on the app server, restarted services, and finally was able to see `إضافة منشور ZZZ` and `تقديم YYY`.

Thank you very much!

**Comment by Agrendalath** [comment]
@0x29a, this looks great. Thank you for providing all references to upstream PRs, backports, and commits, and for testing these changes!

I have only these small comments, but they are not a blocker.

Can we rebase `opencraft-release/maple.3` on `open-release/maple.master`, and then rebase this branch? Let's include [this commit](https://github.com/openedx/configuration/commit/4103567846d806cd06e6f90d5a226dfbf20c4a92) and drop 8fdc460d3925073a2b06d5a59c6eb75ee8f9a066 this way.


>  white_check_mark https://github.com/open-craft/configuration/pull/159: I had to add features manually to the /edx/etc/lms.yml, as I made a mistake in a suggested configuration, and executed python manage.py cms reindex_course --all. It worked fine.

Nit: see [my comment ](https://tasks.opencraft.com/browse/BB-5857?focusedCommentId=249673&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-249673) (quoted below for convenience) on the internal ticket. This is not the correct way to test this, but my explanation is enough for me to give a +1 for this cherry-pick. We might need small adjustments for this solution, but it's not in the scope of the current PR.

> In short - we're deploying ElasticSearch on each Ocim sandbox, so the search data is stored only locally. Therefore, we need to rebuild it after each deployment. Moving it to the forum playbook to make it run after the local ElasticSearch playbook technically works, but we can achieve a more elegant (and upstreamable) solution by moving [the ES role](https://github.com/openedx/configuration/blob/bd1f52aff62869f2d1214827fca70665e5e245d3/playbooks/openedx_native.yml#L116-L117) above `edxapp`.
> 
> As long as we have only one active AppServer at a time, this is going to work. If we want to achieve data persistence, we should either deploy a dedicated ES or wait until [SE-5362](https://tasks.opencraft.com/browse/SE-5362) is completed.
> 
> I just don't understand why we've changed `--setup` to `--all`. The main difference is [disabling the confirmation](https://github.com/openedx/edx-platform/blob/open-release/ginkgo.1/cms/djangoapps/contentstore/management/commands/reindex_course.py#L102-L103) for a non-interactive session, which sounds like something we would like to keep.

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x]  I tested this: verified testing instructions from upstream and testing steps from this
* [x]  I read through the code
* [x]  I checked for accessibility issues: n/a
* [x]  Includes documentation: n/a
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

**Pull request merged**
