### PR TITLE
fix xqueue version

### PR DESCRIPTION
**Pull request by pkulkark**
The edX xqueue `master` branch uses django 2.2.9 which fails to install with our ironwood branch playbook. This PR updates the xqueue playbook to use the `open-release/ironwood.master` branch instead.

### CODE REVIEW

**Comment by pomegranited** [comment]
Thanks @pkulkark  -- edX did this recently with https://github.com/edx/configuration/pull/5618, and used `OPENEDX_RELEASE` to set `XQUEUE_VERSION`.

Could you do the same here?  That will make the `XQUEUE_VERSION` be the tagged [open-release/ironwood.2](https://github.com/edx/xqueue/tree/open-release/ironwood.2) instead.

**Comment by pkulkark** [comment]
@pomegranited I was going to do that but then I noticed we're using [edx/xqueue](https://github.com/edx/xqueue) and not [open-craft/xqueue](https://github.com/open-craft/xqueue) (I'm not sure why). edx/xqueue only has the `open-release/ironwood.master` branch.

**Comment by pomegranited** [comment]
@pkulkark There's a tag in edx/xqueue for ironwood.2: https://github.com/edx/xqueue/tree/open-release/ironwood.2 , so it should be ok to use that?  The only [difference](https://github.com/edx/xqueue/compare/open-release/ironwood.2...open-release/ironwood.master) is with the base Django version, so it's not a big deal, but it also [matches what we do for Ocim](https://github.com/open-craft/opencraft/blob/74e0808642b8bd4d29d2dcb12c4147665eec09e0/instance/models/mixins/openedx_config.py#L176).

**Comment by pkulkark** [comment]
@pomegranited Ah I didn't notice that, Sorry! Also I just realized that epodx was passing `xqueue_version` instead of `XQUEUE_VERSION` which probably explains why it wasn't getting picked. I raised a separate PR for that in the epodX repo. This change won't be needed then. Will close this.

**Pull request closed without merging**
