### PR TITLE
Prepare opencraft-release/nutmeg.2 branch for configuration

### PR DESCRIPTION
**Pull request by Cup0fCoffee**
### Description

This PR prepares the shared `opencraft-release/nutmeg.2` branch for our fork of https://github.com/openedx/configuration.

[Code drift commits](https://github.com/openedx/configuration/compare/open-release/maple.3...open-craft:configuration:opencraft-release/maple.3)
or
```bash
git log opencraft/opencraft-release/maple.3 ^open-release/maple.3 --graph
```

| Commit                                     | Related Task                                            | Upstream PR                                                                                             | Included in `open-release/nutmeg.2`   | Should be cherry-picked?   | Notes                                                                                                                                                                                                                                   |
| ------------------------------------------ | ------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- | ------------------------------------- | -------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 70062bb9bff88713437307693222c1259ba48fb1   | :x:                                                     | https://github.com/openedx/configuration/commit/e33f2ed692b231f6e3703f77e3d49f4a30e29557                | :heavy_check_mark:                    | :x:                        | Has been ported to both Nutmeg and master.                                                                                                                                                                                              |
| 4103567846d806cd06e6f90d5a226dfbf20c4a92   | :x:                                                     | https://github.com/openedx/configuration/pull/6746                                                      | :heavy_check_mark:                    | :x:                        | Has been ported to both Nutmeg and master.                                                                                                                                                                                              |
| a1b6ce4998e4b14f323b4ef1f3a0981d609f3de6   | [SE-4419](https://tasks.opencraft.com/browse/SE-4419)   | :x:                                                                                                     | :x:                                   | :heavy_check_mark:         |                                                                                                                                                                                                                                         |
| 459da2950c552d8f1fda426c1cf89db1cdeb6018   | [SE-4364](https://tasks.opencraft.com/browse/SE-4364)   | :x:                                                                                                     | :x:                                   | :heavy_check_mark:         | As far as I can tell from reading the comments, there was no budget for upstreaming and it was determined that it's not worth it.                                                                                                       |
| 6e7281a9f84b672563feb4ab9d08ef4b5bca5282   | :x:                                                     | :x:                                                                                                     | :x:                                   | :heavy_check_mark:         | ~Based on the commit message, it doesn't seem like this needs to be cherry picked any more.~ https://github.com/open-craft/configuration/pull/207#pullrequestreview-1128709658                                                          |
| a1a482ad9ecd8ba43d3957d58901eede36fd5cce   | [SE-5299](https://tasks.opencraft.com/browse/SE-5299)   | https://github.com/openedx/configuration/pull/6677                                                      | :heavy_check_mark:                    | :x:                        | Upstreamed.                                                                                                                                                                                                                             |
| 64811929107f4f08ad1d1f93861e10752d97d94b   | [SE-5140](https://tasks.opencraft.com/browse/SE-5140)   | https://github.com/openedx/configuration/pull/6679                                                      | :heavy_check_mark:                    | :x:                        | Upstreamed.                                                                                                                                                                                                                             |
| 225cb1a856b785558ad7629cb46064584481b40e   | [SE-5140](https://tasks.opencraft.com/browse/SE-5140)   | https://github.com/openedx/configuration/pull/6708                                                      | :heavy_check_mark:                    | :x:                        | Upstreamed.                                                                                                                                                                                                                             |
| 0248d9900db5c62a94c1c3388643f7f1f13baba8   | :x:                                                     | https://github.com/openedx/configuration/pull/6717                                                      | :x:                                   | :x:                        | Wasn't ported to `open-release/nutmeg.2`, because the same issue was fixed two days later by 1f4ff355d9df684a215617ea7e3d8802864b6f8a in master (cherry picked to `open-release/nutmeg.2` in 70062bb9bff88713437307693222c1259ba48fb1). |
| 537f65f9a430545cfb0374a1b1282aa378c9d479   | [BB-6112](https://tasks.opencraft.com/browse/BB-6112)   | :x:                                                                                                     | :x:                                   | :x:                        | Merge commit.                                                                                                                                                                                                                           |
| 9e16e88d2a3ef875e234dd62c08101c71fb082ab   | [BB-6154](https://tasks.opencraft.com/browse/BB-6154)   | https://github.com/openedx/configuration/pull/6755                                                      | :x:                                   | :heavy_check_mark:         | Was upstreamed but is missing in `nutmeg.2` tag.                                                                                                                                                                                        |
| 0f0fd1867fe238ab5e79c0288829d305c95d76ba   | [SE-5708](https://tasks.opencraft.com/browse/SE-5708)   | https://github.com/openedx/configuration/pull/6772                                                      | :heavy_check_mark:                    | :x:                        | Has been ported to both Nutmeg and master.                                                                                                                                                                                              |
| 688dc7a2bec7b2addd40dbac25a5b2af47e478a1   | [SE-4860](https://tasks.opencraft.com/browse/SE-4860)   | https://github.com/openedx/configuration/pull/6586                                                      | :heavy_check_mark:                    | :x:                        | Upstreamed.                                                                                                                                                                                                                             |
| 4ed5b986c3b08fcca979d3d908832016389b23e3   | [SE-4860](https://tasks.opencraft.com/browse/SE-4860)   | :x:                                                                                                     | :x:                                   | :heavy_check_mark:         | ~Need to double check, since there are no references.~ If the affected services are now using Celery 5, this commit can be skipped. Need to test. https://github.com/open-craft/configuration/pull/194                                  |
| 7e853a5ad98af1b1919df1924dc4ac1bc68a988c   | :x:                                                     | https://github.com/openedx/configuration/pull/6612                                                      | :heavy_check_mark:                    | :x:                        | Upstreamed.                                                                                                                                                                                                                             |
| 0c8c3163e7f629f3da615e726b2edd52f303f440   | :x:                                                     | https://github.com/openedx/configuration/pull/6693                                                      | :heavy_check_mark:                    | :x:                        | Upstreamed.                                                                                                                                                                                                                             |
| 665cc3f7d186004e685e4b97e644289e59e37f5a   | [BB-6383](https://tasks.opencraft.com/browse/BB-6383)   | https://github.com/openedx/configuration/pull/6773                                                      | :x:                                   | :heavy_check_mark:         | Was merged into master after the nutmeg.2 was created, and wasn't backported to it. Going to cherry pick the merge commit from the master branch (33baf7c594c3c0b3bfeea10ea16b82a33eabb431).                                            |
| 09cdc0bdb9402d01d2476793ad4668fcd2aeb135   | [BB-6383](https://tasks.opencraft.com/browse/BB-6383)   | https://github.com/openedx/configuration/pull/6773                                                      | :x:                                   | :x:                        | Merge commit of the backport.                                                                                                                                                                                                           |
| 476236a52c15d1edbec19204a9baf7f1589e0e4b   | [BB-5885](https://tasks.opencraft.com/browse/BB-5885)   | https://github.com/openedx/configuration/pull/6706                                                      | :heavy_check_mark:                    | :x:                        | Upstreamed.                                                                                                                                                                                                                             |
| 8903ffed2a191c750b85545a00130d339a0ff14a   | [BB-5823](https://tasks.opencraft.com/browse/BB-5823)   | :x:                                                                                                     | :x:                                   | :heavy_check_mark:         | Should ask Pooja if this change is still necessary.                                                                                                                                                                                     |
| 4eb14b0529a7d50db7da73559de0390accb8ae51   | [BB-6458](https://tasks.opencraft.com/browse/BB-6458)   | https://github.com/openedx/configuration/pull/6783 https://github.com/openedx/configuration/pull/6784   | :heavy_check_mark:                    | :x:                        | It's in nutmeg branch, but was [reverted in master](https://github.com/openedx/configuration/pull/6783#issuecomment-1206618663).                                                                                                        |
| d3905112242f983d990d97344b871e1fbbf17195   | [BB-6458](https://tasks.opencraft.com/browse/BB-6458)   | https://github.com/openedx/configuration/pull/6783 https://github.com/openedx/configuration/pull/6784   | :heavy_check_mark:                    | :x:                        | It's in nutmeg branch, but was [reverted in master](https://github.com/openedx/configuration/pull/6783#issuecomment-1206618663).                                                                                                        |
| 3680ae49c5b30f8c3d9dab7d8179455198ecd542   | [BB-6458](https://tasks.opencraft.com/browse/BB-6458)   | https://github.com/openedx/configuration/pull/6783 https://github.com/openedx/configuration/pull/6784   | :heavy_check_mark:                    | :x:                        | It's in nutmeg branch, but was [reverted in master](https://github.com/openedx/configuration/pull/6783#issuecomment-1206618663).                                                                                                        |
| fb455838760bd13061a9a2d741522db9c74a93c5   | ?                                                       | https://github.com/openedx/configuration/pull/6788 https://github.com/openedx/configuration/pull/6792   | :x:                                   | :x:                        | It has been merged (91569325dd907971ce2e6d426dc512dc53a797f0) into `nutmeg.master` branch after `nutmeg.2` was tagged. Don't need to cherry pick, since basing on `openedx/open-release/nutmeg.master`.                                 |
| f088cf0bcfa449745edf5876917d1d616a1af43a   | ?                                                       | https://github.com/openedx/configuration/pull/6788 https://github.com/openedx/configuration/pull/6792   | :x:                                   | :x:                        | Merge commit.                                                                                                                                                                                                                           |
| 21ce48e42ae82c99f395c7d3bf103c427d721987   | [BB-6428](https://tasks.opencraft.com/browse/BB-6428)   | :x:                                                                                                     | :x:                                   | :x:                        | Tbh, idk if it's needed. Will cherry pick the merge below.                                                                                                                                                                              |
| c6f4b930a77625fc4a1632d93f6d9614ca12ac6d   | [BB-6428](https://tasks.opencraft.com/browse/BB-6428)   | :x:                                                                                                     | :x:                                   | :heavy_check_mark:         | Merge commit.                                                                                                                                                                                                                           |

### Testing instructions

#### a1b6ce4998e4b14f323b4ef1f3a0981d609f3de6
Verify:
* Script is placed in the expected place
* Cron job is added

#### 459da2950c552d8f1fda426c1cf89db1cdeb6018
Set `EDXAPP_REINDEX_ALL_COURSES: true` and check the deployment logs contain `TASK [forum : reindex all courses]` without errors.

#### 6e7281a9f84b672563feb4ab9d08ef4b5bca5282
* Ssh into the app server
* ```bash
  cd /edx/app/retirement_service/tubular/
  sudo -u edx_retirement_worker bash
  git status
  ```
* Verify that `open-release/nutmeg.2` version is checked out, instead of the master one

#### 9e16e88d2a3ef875e234dd62c08101c71fb082ab
Follow testing instructions of the [upstream PR](https://github.com/openedx/configuration/pull/6755).

#### 665cc3f7d186004e685e4b97e644289e59e37f5a
Follow testing instructions of the [upstream PR](https://github.com/openedx/configuration/pull/6773).

#### 8903ffed2a191c750b85545a00130d339a0ff14a
https://github.com/openedx/configuration/commit/8903ffed2a191c750b85545a00130d339a0ff14a#commitcomment-85662652

#### c6f4b930a77625fc4a1632d93f6d9614ca12ac6d
Verify that the deployed script has the white space.

---

`Private-ref`: [BB-6693](https://tasks.opencraft.com/browse/BB-6693)

### CODE REVIEW

**Comment by Cup0fCoffee** [comment]
Skipped https://github.com/open-craft/configuration/commit/4ed5b986c3b08fcca979d3d908832016389b23e3 for now, since it's not clear if it's chery-pickable without breaking stuff.

**Comment by Cup0fCoffee** [comment]
> Skipped [4ed5b98](https://github.com/open-craft/configuration/commit/4ed5b986c3b08fcca979d3d908832016389b23e3) for now, since it's not clear if it's chery-pickable without breaking stuff.

https://github.com/openedx/configuration/commit/4ed5b986c3b08fcca979d3d908832016389b23e3#commitcomment-85272707

**Review by 0x29a — APPROVED** [review]
@Cup0fCoffee, a few notes:
- https://github.com/open-craft/configuration/commit/21ce48e42ae82c99f395c7d3bf103c427d721987: yes, it's needed, at least for ASU YTP.
- https://github.com/open-craft/configuration/commit/6e7281a9f84b672563feb4ab9d08ef4b5bca5282: not sure how and why I missed documenting this. 2U (or tCRIL?) [do tag](https://github.com/openedx/tubular/tree/open-release/nutmeg.2) `tubular` package. But, [it's unpinned for named releases](https://github.com/openedx/configuration/blob/733acdcb1241db08f19063d4edde34360af2c03b/playbooks/roles/user_retirement_pipeline/defaults/main.yml#L34). So, each time we deploy an app server, the latest version of `tubular` is fetched. We've had issues exactly because of this. Some `tubular`'s dependency has been bumped, but it wasn't compatible with the installed Python version. We've reported this to edX, and they promised to pin it next time... So, to be on a safer side, let's pin it to the `open-release/nutmeg.2`. You can cherry-pick and modify the original commit, or change [this line](https://github.com/openedx/configuration/blob/733acdcb1241db08f19063d4edde34360af2c03b/playbooks/roles/user_retirement_pipeline/defaults/main.yml#L34).
- Not sure if you got the notification, but I asked Pooja how we can test https://github.com/openedx/configuration/commit/8903ffed2a191c750b85545a00130d339a0ff14a#commitcomment-85662652 and she provided some info. You can specify the related task in the table.
- https://github.com/open-craft/configuration/commit/665cc3f7d186004e685e4b97e644289e59e37f5a: deployment of the app server has failed when this was enabled. AWS agent was trying to query EC2 metadata endpoint and failed, because the VM is outside AWS network. We'll have to test this on UQ's staging.

Aside `tubular`-related note, everything looks good to me and I'm conditionally approving the PR. :+1:

:+1:

- [ ] I didn't test this, only verified that all needed commits are in place.
- [x] I read through the changes.
- [x] Includes documentation.

**Comment by Cup0fCoffee** [comment]
@0x29a Here are my testing results:

https://github.com/open-craft/configuration/commit/a1b6ce4998e4b14f323b4ef1f3a0981d609f3de6 - I checked that the script is deployed and cron task is setup. I've also checked that the script is called correctly (i.e. it doesn't throw errors like `python: command not found` or missing dependencies). I've verified that it fetches the data correctly by using ESME's creds for NewRelic, but I didn't go through the trouble of setting up a custom S3 bucket, because I think the aforementioned steps guarantee that it would work.

https://github.com/open-craft/configuration/commit/459da2950c552d8f1fda426c1cf89db1cdeb6018 - checked the deployment logs, and the reindexing went without errors.

https://github.com/open-craft/configuration/commit/9e16e88d2a3ef875e234dd62c08101c71fb082ab - called the script and made sure it reaches the `python3 ...` line, and doesn't throw `python3: command not found` error.

https://github.com/open-craft/configuration/commit/665cc3f7d186004e685e4b97e644289e59e37f5a - didn't test, based on your comment:
> deployment of the app server has failed when this was enabled. AWS agent was trying to query EC2 metadata endpoint and failed, because the VM is outside AWS network. We'll have to test this on UQ's staging.

https://github.com/open-craft/configuration/commit/8903ffed2a191c750b85545a00130d339a0ff14a - doesn't work correctly. Needs `/usr/bin/python3` [here](https://github.com/openedx/configuration/commit/8903ffed2a191c750b85545a00130d339a0ff14a#diff-b0e6dcdf3b103e1f13d589b60b383e09b48c33e8212a3f9562ff1b433f09a1bcR20), because `/usr/bin/python` throws `: command not found` error.

https://github.com/open-craft/configuration/commit/c6f4b930a77625fc4a1632d93f6d9614ca12ac6d - verified that the white space is in the deployed script, but didn't verify that it works, because I think it's not necessary, since looks the same as the code in the `if` branch.

> not sure how and why I missed documenting this. 2U (or tCRIL?) [do tag](https://github.com/openedx/tubular/tree/open-release/nutmeg.2) tubular package. But, [it's unpinned for named releases](https://github.com/openedx/configuration/blob/733acdcb1241db08f19063d4edde34360af2c03b/playbooks/roles/user_retirement_pipeline/defaults/main.yml#L34). So, each time we deploy an app server, the latest version of tubular is fetched. We've had issues exactly because of this. Some tubular's dependency has been bumped, but it wasn't compatible with the installed Python version. We've reported this to edX, and they promised to pin it next time... So, to be on a safer side, let's pin it to the open-release/nutmeg.2. You can cherry-pick and modify the original commit, or change [this line](https://github.com/openedx/configuration/blob/733acdcb1241db08f19063d4edde34360af2c03b/playbooks/roles/user_retirement_pipeline/defaults/main.yml#L34).

Good catch. I'll add to the commit message so it's more clear in the future.

> Not sure if you got the notification, but I asked Pooja how we can test https://github.com/openedx/configuration/commit/8903ffed2a191c750b85545a00130d339a0ff14a#commitcomment-85662652 and she provided some info. You can specify the related task in the table.

Yep, I saw the notification, but missed the fact that Pooja linked a ticket. Going to add it to the table.

https://github.com/open-craft/configuration/commit/4ed5b986c3b08fcca979d3d908832016389b23e3 - perhaps you can help me with this one? Short story is that we need this commit if services haven't upgraded to from Celery 4 to 5. But the issue is that, course discovery, for example, is using Celery 5, so this commit would not work with it, and at the same time the other services, like ecommerce are still using Celery 4, so they need this commit. I'll continue thinking about it, but any suggestions are welcome.

**Comment by 0x29a** [comment]
>https://github.com/open-craft/configuration/commit/4ed5b986c3b08fcca979d3d908832016389b23e3 - perhaps you can help me with this one? Short story is that we need this commit if services haven't upgraded to from Celery 4 to 5. But the issue is that, course discovery, for example, is using Celery 5, so this commit would not work with it, and at the same time the other services, like ecommerce are still using Celery 4, so they need this commit. I'll continue thinking about it, but any suggestions are welcome.

@Cup0fCoffee, as both ecommerce and course discovery inherit the same role, I think we'll need to add three new variables, like [here](https://github.com/openedx/configuration/pull/6400/files), and an if clause to the `app-workers.conf.j2` template. Something like `edx_django_service_celery_arguments_format` (`old` or `new`), `ECOMMERCE_CELERY_ARGUMENTS_FORMAT`, `DISCOVERY_CELERY_ARGUMENTS_FORMAT`.

**Comment by Cup0fCoffee** [comment]
@0x29a

8903ffed2a191c750b85545a00130d339a0ff14a - changed the template and tested that it works.

6e7281a9f84b672563feb4ab9d08ef4b5bca5282 - cherry-picked and added more verbose commit message adaf78dd34d07268f9442aaf4aa55dd8042f1dfa.

4ed5b986c3b08fcca979d3d908832016389b23e3 - after some testing, I don't think this fix is necessary. `ecomworker` works without this patch, and the other services which we are using are upgraded to Celery 5. `ecommerce` still has Celery 4 pinned, but it's not using a worker in the same ways as discovery does, so it's not using the same template.

**Pull request merged**
